# src/broker_api.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol, Optional

@dataclass
class Order:
    symbol: str
    side: str            # "buy" | "sell"
    qty: float
    order_type: str = "market"    # "market" | "limit"
    limit_price: Optional[float] = None
    tag: str = ""

class BrokerAPI(Protocol):
    def now(self): ...
    def cash(self) -> float: ...
    def equity(self) -> float: ...
    def get_position(self, symbol: str) -> float: ...
    def submit_order(self, order: Order): ...
    def cancel(self, order_id): ...
    def log(self, *a, **k): ...
    def debug(self, *a, **k): ...
    def error(self, *a, **k): ...
