# src/platform/base.py
from typing import Protocol, Callable
from datetime import datetime


class IAlgoHost(Protocol):
    # --- time & state ---
    @property
    def now(self) -> datetime: ...
    def get_portfolio_value(self) -> float: ...
    def get_cash(self) -> float: ...

    # --- logging ---
    def log_info(self, msg: str, component: str = "") -> None: ...
    def log_warning(self, msg: str, component: str = "") -> None: ...
    def log_error(self, msg: str, component: str = "") -> None: ...

    # --- orders ---
    def market_order(self, symbol, quantity: float) -> None: ...

    # --- scheduling (normalized) ---
    def schedule_hourly(self, callback: Callable[[], None]) -> None: ...
    def schedule_open(self, callback: Callable[[], None]) -> None: ...
    def schedule_close(self, callback: Callable[[], None]) -> None: ...
    def schedule_eod(self, callback: Callable[[], None]) -> None: ...
